<template lang='pug'>
  v-container(fluid, grid-list-lg)
    v-layout(row wrap)
      v-flex(xs12)
        .admin-header
          img.animated.fadeInUp(src='/_assets/svg/icon-file.svg', alt='Page Import', style='width: 80px;')
          .admin-header-title
            .headline.blue--text.text--darken-2.animated.fadeInLeft Bulk Import
            .subtitle-1.grey--text.animated.fadeInLeft.wait-p2s Import markdown pages from a ZIP package
          v-spacer
          v-btn.animated.fadeInDown(color='grey', outlined, large, to='/pages')
            v-icon(left) mdi-arrow-left
            span Back to Pages
      v-flex(xs12, lg8)
        v-card.animated.fadeInUp
          v-card-text
            v-alert.mb-4(type='info', outlined)
              div Only ZIP packages are supported. The ZIP must contain markdown files directly at the root level. Subdirectories are not supported.
              div.mt-1 Each imported page path is generated automatically using UUID. The article title is taken from the file name.
            .overline.mb-2 Import Target
            v-select.mb-3(
              outlined
              dense
              label='Locale'
              :items='namespaces'
              v-model='locale'
              :disabled='loading'
            )
            v-text-field.mb-3(
              outlined
              dense
              readonly
              label='Target Directory'
              :value='targetPathDisplay'
              :disabled='loading'
              append-icon='mdi-folder-search-outline'
              @click='folderSelectorShown = true'
              @click:append='folderSelectorShown = true'
            )
            .overline.mb-2 ZIP Package
            v-file-input(
              outlined
              dense
              show-size
              accept='.zip,application/zip,application/x-zip-compressed'
              prepend-icon='mdi-archive-outline'
              label='Choose ZIP package'
              v-model='zipFile'
              :disabled='loading'
            )
          v-divider
          v-card-actions
            v-spacer
            v-btn(text, to='/pages', :disabled='loading') Cancel
            v-btn(color='primary', depressed, :loading='loading', :disabled='!canImport', @click='importPages')
              v-icon(left) mdi-upload
              span Import
      v-flex(xs12, lg4)
        v-card.animated.fadeInUp.wait-p1s
          v-card-title Import Rules
          v-card-text
            v-list(dense)
              v-list-item
                v-list-item-icon: v-icon(color='primary') mdi-folder-outline
                v-list-item-content
                  v-list-item-title Choose a target directory first.
              v-list-item
                v-list-item-icon: v-icon(color='primary') mdi-identifier
                v-list-item-content
                  v-list-item-title Page paths are generated by UUID.
              v-list-item
                v-list-item-icon: v-icon(color='primary') mdi-format-title
                v-list-item-content
                  v-list-item-title Article titles use file names.
              v-list-item
                v-list-item-icon: v-icon(color='primary') mdi-language-markdown-outline
                v-list-item-content
                  v-list-item-title Markdown files only.
              v-list-item
                v-list-item-icon: v-icon(color='primary') mdi-folder-off-outline
                v-list-item-content
                  v-list-item-title ZIP subdirectories are rejected.
      v-flex(xs12, v-if='imported.length || failed.length')
        v-card.animated.fadeInUp
          v-card-title Import Result
          v-card-text
            v-alert(v-if='imported.length', type='success', outlined)
              div {{ imported.length }} page(s) imported successfully.
            v-data-table.mb-4(
              v-if='imported.length'
              :headers='importedHeaders'
              :items='imported'
              dense
              hide-default-footer
              :items-per-page='-1'
            )
              template(slot='item.path', slot-scope='props')
                code /{{ props.item.path }}
            v-alert(v-if='failed.length', type='error', outlined)
              div {{ failed.length }} file(s) failed to import.
            v-data-table(
              v-if='failed.length'
              :headers='failedHeaders'
              :items='failed'
              dense
              hide-default-footer
              :items-per-page='-1'
            )
    page-selector(mode='select', folders-only, v-model='folderSelectorShown', :open-handler='selectTarget', :locale='locale', :path='targetPath || `home`')
</template>

<script>
import Cookies from 'js-cookie'

/* global siteLangs, siteConfig */

export default {
  data() {
    return {
      folderSelectorShown: false,
      locale: siteConfig.lang,
      targetPath: '',
      zipFile: null,
      loading: false,
      imported: [],
      failed: [],
      importedHeaders: [
        { text: 'File', value: 'fileName' },
        { text: 'Title', value: 'title' },
        { text: 'Path', value: 'path' }
      ],
      failedHeaders: [
        { text: 'File', value: 'fileName' },
        { text: 'Title', value: 'title' },
        { text: 'Path', value: 'path' },
        { text: 'Error', value: 'message' }
      ]
    }
  },
  computed: {
    namespaces () {
      return siteLangs.length ? siteLangs.map(ns => ns.code) : [siteConfig.lang]
    },
    targetPathDisplay () {
      return this.targetPath ? `/${this.targetPath}` : '/'
    },
    canImport () {
      return this.zipFile && !this.loading
    }
  },
  methods: {
    selectTarget ({ locale, path }) {
      this.locale = locale
      this.targetPath = path === 'home' ? '' : path
    },
    async importPages () {
      if (!this.zipFile) { return }
      this.loading = true
      this.imported = []
      this.failed = []
      try {
        const form = new FormData()
        form.append('locale', this.locale)
        form.append('path', this.targetPath)
        form.append('pageImport', this.zipFile)

        const resp = await fetch('/a/pages/import', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${Cookies.get('jwt')}`
          },
          body: form
        })
        const result = await resp.json()
        if (!resp.ok || !result.succeeded) {
          this.$store.commit('showNotification', {
            message: result.message || 'Page import failed.',
            style: result.imported && result.imported.length ? 'warning' : 'error',
            icon: 'warning'
          })
        } else {
          this.$store.commit('showNotification', {
            message: result.message,
            style: 'success',
            icon: 'check'
          })
        }
        this.imported = result.imported || []
        this.failed = result.failed || []
      } catch (err) {
        this.$store.commit('showNotification', {
          message: err.message,
          style: 'error',
          icon: 'warning'
        })
      }
      this.loading = false
    }
  }
}
</script>
